export const hair = document.getElementById('hair')
export const dress = document.getElementById('dress')
export const broom = document.getElementById('broom')
export const cognitz = document.getElementById('cognitz')
export const itemsHolder = document.getElementById('items')